tuples= ("apple", "banana", "cherry","orange", "kiwi", "melon", "mango")
print(tuples)
print(len(tuples))
print(type(tuples))
print(tuples[1])
print((tuples[2:5]))
y= list(tuples)
y[1]= "kiwi"
y.append("watermilon")
tuples= tuple(y)
print(tuples)
y = list(tuples)
y.remove("apple")
tuples= tuple(y)
print(tuples)
